name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DISCORD_WEBHOOK_URL: https://discord.com/api/webhooks/1278820756431835267/8mVE4eqxipyVl2gknjQE98NwYldfl7Brs8q-VlwmbcVEyUn0kR6W8dpACGHCdhhRcDLT

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Run tests
      run: npm run test

    - name: Send Discord notification
      if: always()
      run: |
        if [[ "${{ job.status }}" == "success" ]]; then
          discordMessage="All tests passed!"
        else
          discordMessage="Unfortunately, some tests failed."
        fi

        curl -H "Content-Type: application/json" -d "{\"content\": \"**Build #${{ github.run_number }}** - $discordMessage. See the results at ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}\"}" ${{ env.DISCORD_WEBHOOK_URL }}
