name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  GIT_REPO: https://github.com/fdanilon/api-tests-jest
  DISCORD_WEBHOOK_URL: https://discord.com/api/webhooks/1278820756431835267/8mVE4eqxipyVl2gknjQE98NwYldfl7Brs8q-VlwmbcVEyUn0kR6W8dpACGHCdhhRcDLT

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Cloning the repository
      uses: actions/checkout@v3
      with:
        repository: ${{ env.GIT_REPO }}
        ref: master

    - name: Run tests
      run: ./npm run test

    - name: Publish test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: Test Results
        path: '**/target/surefire-reports/TEST-*.xml'

    - name: Send Discord notification
      if: always()
      run: |
        if [[ "${{ job.status }}" == "success" ]]; then
          discordMessage="All tests passed!"
        else
          discordMessage="Unfortunately, some tests failed."
        fi
        
        curl -H "Content-Type: application/json" -d "{\"content\": \"**Build #${{ github.run_number }}** - $discordMessage. See the results at ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}\"}" ${{ env.DISCORD_WEBHOOK_URL }}
